### ISSUE TITLE
How long does it take to train LC_Rec

### ISSUE THREAD

**Issue by ManagerYu10** [RUCAIBox/LC-Rec#1]
Hi~Firstly, thanks for your great contributaion.
May I ask how long did it take to train your model, under the Implementation Details in your paper?
Thanks in advance!

**Comment by zhengbw0324** [comment]
@YuZhang10 
For the Games dataset, it takes approximately 12 hours of training on 8 40G A100 GPUs.

**Comment by ManagerYu10** [comment]
O, one more question, have you ever tried LoRA or other partial parameter tuning method? Are those method significantly inferior to full parameter tuning? Thanks~
