### ISSUE TITLE
请问一下关于 sft_prompt 的问题

### ISSUE THREAD

**Issue by Snowilv** [RUCAIBox/LC-Rec#10]
您好，在构建训练和测试数据集中我注意到训练集的 input 和 [output](https://github.com/RUCAIBox/LC-Rec/blob/4dde5da38ef67180330b773c4890fe75e78f8524/data.py#L245) 通过 [sft_prompt](https://github.com/RUCAIBox/LC-Rec/blob/4dde5da38ef67180330b773c4890fe75e78f8524/data.py#L248) 模板构建的，请问为什么 output 要重复一遍 input 的内容呢？
此外，测试集的 [output](https://github.com/RUCAIBox/LC-Rec/blob/4dde5da38ef67180330b773c4890fe75e78f8524/data.py#L248) 直接使用了 {item} 并没有重复 input， 这里可以麻烦解释一下嘛

**Comment by Snowilv** [comment]
[sft_prompt ](https://github.com/RUCAIBox/LC-Rec/blob/4dde5da38ef67180330b773c4890fe75e78f8524/prompt.py#L3)链接重新设置了下，原文中链接错了

**Comment by zhengbw0324** [comment]
@Snowilv 
您好！很高兴您关注到我们的工作。
https://github.com/RUCAIBox/LC-Rec/blob/4dde5da38ef67180330b773c4890fe75e78f8524/data.py#L245
这里这样构建output的目的是在获取训练所需要的labels时保证response的位置准确。
距离的处理方式您可以参考这里：
https://github.com/RUCAIBox/LC-Rec/blob/4dde5da38ef67180330b773c4890fe75e78f8524/collator.py#L28-L42
举例来说的话就是假设inputs_ids=[1,2,3,4,5,6,7,8], 其中“6,7,8”是response，那么我们需要的labels=[[-100,-100,-100,-100,-100,6,7,8]]，这里-100是忽略该部分损失的意思。具体您可以参考pytorch CrossEntropyLoss的文档。

**Comment by Snowilv** [comment]
问题解决了！感谢您及时的回复～

**Comment by Snowilv** [comment]
你好还有一个小问题，初始化tokenizer时为什么要设置 [pad_id = 0](https://github.com/RUCAIBox/LC-Rec/blob/4dde5da38ef67180330b773c4890fe75e78f8524/finetune.py#L36) 呢，这样会不会与原本 token_id = 0 的 token 有冲突

**Comment by zhengbw0324** [comment]
@Snowilv 
LLaMA的pad_id就是0，当时是刚开始用的ckpt有点问题，手动修复了一下，现在可以去掉，不影响。

**Comment by Snowilv** [comment]
好的明白了，感谢您的解答
