### ISSUE TITLE
请问一下关于开源权重的问题

### ISSUE THREAD

**Issue by jkdwxm** [RUCAIBox/LC-Rec#11]
您好！我按照`README/Model Checkpoint`下载了Llama和Delta权重，并用`merge_delta.py`脚本进行了合并，但我使用`test.sh`测试发现指标皆为0，请问为什么会这样呢？谢谢！

**Comment by zhengbw0324** [comment]
@jkdwxm

**Comment by zhengbw0324** [comment]
@jkdwxm 
您好，我重新测试了代码，并没有发现问题，您可能需要注意将`CKPT_PATH`设置为融合后的参数路径而不是delta参数路径。

**Comment by jkdwxm** [comment]
@zhengbw0324 十分感谢！经您提醒，我发现没有正确下载delta权重中tokenizer的added_tokens文件，正确下载后解决了该问题。帮大忙啦，再次感谢！
