### ISSUE TITLE
There is something wrong with the version of the library. Could you please show me the pip list

### ISSUE THREAD

**Issue by shijiesong01** [RUCAIBox/LC-Rec#15]
l run like this
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
pip install accelerate
pip install bitsandbytes
pip install deepspeed
pip install evaluate
pip install peft
pip install sentencepiece
pip install tqdm
pip install transformers
but it always failed and now l can't work it out

**Comment by shijiesong01** [comment]
Hello, when running run.sh, the speed is very slow. How long does it take to run 8 A100s? It took me more than 2 days

**Comment by zhengbw0324** [comment]
@shijie-zju 
Hello, please try to avoid using the latest version of transformers. You can try versions before 4.37.2.

**Comment by zhengbw0324** [comment]
Regarding the running time, you can refer to [issue #1](https://github.com/RUCAIBox/LC-Rec/issues/1)

**Comment by shijiesong01** [comment]
> Regarding the running time, you can refer to [issue #1](https://github.com/RUCAIBox/LC-Rec/issues/1)

thank you so much!

**Comment by tiebreaker4869** [comment]
same issue regarding versions, do you resolve this issue?
