### ISSUE TITLE
有关

### ISSUE THREAD

**Issue by shijiesong01** [RUCAIBox/LC-Rec#16]
您好，十分感谢您的研究和工作！
在消融实验的复现中，我希望复现TABLE IV中SEQ+MUT对应行的结果
代码的修正体现在对run.sh进行了如下修改：
--tasks seqrec,item2index,index2item

**Comment by shijiesong01** [comment]
然后其他内容没有改变，经过run.sh后得到的final-checkpoint文件作为最终结果，
![image](https://github.com/user-attachments/assets/bfa678e2-1cd7-43df-ba8e-9f51655a35e3)
然后同样进行test_ddp.sh部分的测试，但各项指标没有达到预期，均低0.01-0.02左右
我猜测是由于我在run.sh部分不应仅对task参数作修正，请问在消融实验前是否需要对tasks外的其他参数进行调整，还是我对应其他过程的处理存在问题
（十分感谢~）

**Comment by zhengbw0324** [comment]
@shijie-zju 
您好，建议您尝试不同epoch或step的checkpoint，往往最后一个epoch的checkpoint会出现过拟合现象，您可以尝试一下第2或第3个epoch的checkpoint。

**Comment by shijiesong01** [comment]
好的，十分感谢您的帮助，我尝试一下！
非常感谢~
