### ISSUE TITLE
你好请问关于生成结果的问题

### ISSUE THREAD

**Issue by Snowilv** [RUCAIBox/LC-Rec#17]
你好，我使用提供的脚本训练完测试时打印了结果，基本所有结果的beam search基本都是一样的，导致ndcg非常高，而且hit偏低，请问是哪里出问题了呢
predictions:['<a_111><b_213><c_139><d_121>', '<a_111><b_213><c_139><d_121>', '<a_111><b_213><c_139><d_121>', '<a_111><b_213><c_139><d_121>', '<a_111><b_213><c_139><d_121>', '<a_111><b_213><c_139><d_121>', '<a_111><b_213><c_139><d_121>', '<a_197><b_177><c_57><d_17>', '<a_197><b_177><c_57><d_17>', '<a_197><b_177><c_57><d_17>', '<a_197><b_177><c_57><d_17>', '<a_197><b_177><c_57><d_17>', '<a_197><b_177><c_57><d_17>', '<a_197><b_177><c_57><d_17>', '<a_111><b_23><c_207><d_19>', '<a_111><b_23><c_207><d_19>', '<a_111><b_23><c_207><d_19>', '<a_197><b_177><c_57><d_143>', '<a_197><b_177><c_57><d_143>', '<a_197><b_177><c_57><d_143>']

**Comment by zhengbw0324** [comment]
@Snowilv 
您好，请在进行beam search生成时设置do_sample=False，新版本的transformers和一些LLM ckpt会默认为True。

**Comment by Snowilv** [comment]
感谢您，问题解决了！
