### ISSUE TITLE
The data for the RQ-VAE training

### ISSUE THREAD

**Issue by xjw-nlp** [RUCAIBox/LC-Rec#3]
Thanks for your impressive work!

For RQ-VAE, currently there seems to be a missing step here in converting the item text into the embedding.

**Comment by zhengbw0324** [comment]
@xjw-nlp 
Hello, this process is in the process of data processing. You can refer to the file [here](https://github.com/RUCAIBox/LC-Rec/blob/main/data_process/amazon_text_emb.py).
