### ISSUE TITLE
Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory

### ISSUE THREAD

**Issue by Snowilv** [RUCAIBox/LC-Rec#4]
运行run_test.sh时报下面的错误：
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/ljs/LC-Rec/ckpt/Games/.

其中 /home/ljs/LC-Rec/ckpt/Games/ 目录下有这些文件：
![image](https://github.com/RUCAIBox/LC-Rec/assets/155278417/49266adc-b63b-4f64-a425-d0cae50c453f)

请问是 OUTPUT_DIR 设置有问题吗

**Comment by zhengbw0324** [comment]
@Snowilv 您好！
您可以尝试使用以final开头的checkpoint文件夹。

**Comment by Snowilv** [comment]
是的我尝试过，但generate的结果中prediction都是空的，就仅仅把输入的prompt给返回了，没有生成新的token，这是为什么呢

**Comment by zhengbw0324** [comment]
@Snowilv
可以尝试把下面这个行注释掉看看结果：
https://github.com/RUCAIBox/LC-Rec/blob/4920017142dfd2962bb4237e96dc984e4471a812/test.py#L97
还有可能是您的训练步数太少了。

**Comment by Snowilv** [comment]
感谢！确实work了，但比较好奇这部分代码其实是有助于提高Recall的，可以控制beam search生成的token...
而且如果只计算到HitRecall@10的话是不是设置 num_beams = 10 就好了呢，还是说 num_beams = 20 也有助于R@1、R@5的提升呢。
因为我运行过程中发现有很多prediction的item都是一样的，按道理如果 num_beams = 10 的话应该生成10种不同的items吧

**Comment by zhengbw0324** [comment]
@Snowilv 
实际上我尝试过num_beams = 10、20或者更大，更大的值确实有助于提高Recall，但其实提升不是很大，且num_beams增大到一定程度就不会再有提升了。
我当时实验过程中，prediction中item并没有出现很多一样的情况，要不您试一下我公开checkpoint？

**Comment by Snowilv** [comment]
好的！感谢您的耐心解答～
